language: rust

rust: 
  - stable

before_cache: rm -rf "$TRAVIS_HOME/.cargo/registry/src"
cache: cargo

jobs:
  include:
    - stages: test
      script:
        - cargo check --verbose
        - cargo test --verbose
    - stages: package
      script: cargo publish --dry-run
    - stages: publish
      script: cargo publish --token $CARGO_TOKEN
      if: commit_message =~ /^#release*/ 

notifications:
  email: false